---
- name: Create user on all managed nodes
  hosts: all
  become: true
  tasks:
   - name: User Creation
     user:
      name: Anto
      password: tonton
      home: /home/Anto
      uid: 123456
      shell: /bin/bash
      comment: "A good devops manager"
...
