---
- name: Create a jenkins and tomcat for CI-CD using docker and ansible
  hosts: all
  become: true
  tasks:
   - name: Create a jenkins container
     docker_container:
      name: myjenkins
      image: jenkins/jenkins
      ports:
       - 5050:8080
   - name: Create a tomcat as QAServer
     docker_container:
      name: QAServer
      image: tomcat
      ports:
       - 6060:8080
      links:
       - myjenkins:jenkins
   - name: Create a tomcat as Prodserver
     docker_container:
      name: ProdServer
      image: tomcat
      ports:
       - 3333:8080
      links:
       - myjenkins:jenkins
...
