---
- name: Create 10 nginx containers
  hosts: all
  become: true
  tasks:
   - name: Create nginx container
     docker_container:
      name: "container{{item}}"
      image: nginx
     with_sequence: count=10              
...
