---
- name: Configuring apache2
  hosts: all
  become: true
  tasks:
   - name: Install apache2
     apt:
      name: apache2
      state: present
      update_cache: yes
   - name: Edit the index.html file
     copy: 
      content: "Hello ADJ"
      dest: /var/www/html/index.html
   - name: Restart apache2 service
     service:
      name: apache2
      state: restarted
   - name: Check url response of apache2 on server1
     uri:
      url: http://172.31.125.129
      status_code: 200
   - name: Check url response of apache2 on server2
     uri:
      url: http://172.31.95.89
      status_code: 200
...
