---
- name: Implementing docker compose using ansible
  hosts: all
  become: true
  tasks:
   - name: Create a mysql container
     docker_container:
      name: mydb
      image: mysql
      env:
       MYSQL_ROOT_PASSWORD: anto
   - name: Create a wordpress container
     docker_container:
      name: mywordpress
      image: wordpress
      ports:
       - 9090:80
      links:
       - mydb:mysql
...
