---
- name: Install/Uninstall s/w applications
  hosts: all
  become: true
  vars:
   - a: tomcat9
   - b: present
   - c: no
  tasks:
   - name: Install/Uninstall
     apt:
      name: "{{a}}"
      state: "{{b}}"
      update_cache: "{{c}}"
...
